### ISSUE TITLE
Unable to prepare setup for platform smartthinq_sensors.sensor: Platform not found

### ISSUE THREAD

**Issue by xMuehlex** [sampsyo/hass-smartthinq#106]
Hello,
I am currently facing the following problem.
I am trying to connect a LG washing machine to HomeAssistant. Unfortunately, only an on/off switch is detected. The detection of the sensors fails with the following error:

LOG:
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 10. Oktober 2021, 12:56:38 (4 occurrences)
Last logged: 10. Oktober 2021, 12:59:41

Unable to prepare setup for platform smartthinq_sensors.sensor: Platform not found (cannot import name 'DEVICE_CLASS_PM1' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform smartthinq_sensors.binary_sensor: Platform not found (cannot import name 'DEVICE_CLASS_PM1' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

Any suggestions?

**Comment by sampsyo** [comment]
Hmm; I don't quite understand these error messages, unfortunately… it seems to be a Python error stemming from an `import` statement, but we never actually import the name `DEVICE_CLASS_PM1`? I'm sort of stumped, but perhaps this could have to do with #105 and therefore @cynicer might have some intuition about what's going wrong?

**Comment by cynicer** [comment]
#105 shouldn't have changed any washing machine logic, let alone interact with an PM1 sensor. Can you provide more logs? Do you have any other thinq devices connected (i.e. AC or anything with PM1 sensor?)?

**Comment by xMuehlex** [comment]
If you tell me where to find more logs, I can provide them.
I do not own any other ThinQ devices.

**Comment by cynicer** [comment]
Ah nvm, this already seems to be the log entry of HA. Which device are you trying to connect? The weird thing is that the problem seems to be in the HA code? Is this classified as "WARNING" or "ERROR"?

**Comment by xMuehlex** [comment]
The message is classified as an error (Fehler).

<img width="1137" alt="Bildschirmfoto 2021-10-14 um 10 31 34" src="https://user-images.githubusercontent.com/89790571/137281526-cceb9b73-2a24-4587-83a5-4b50a7b28a60.png">

The device I want to connect is an LG V5105SE washing machine.

**Comment by xMuehlex** [comment]
EDIT:

Problem solved.
My Home Assistant runs as a Docker container. After changing from "ghcr.io/home-assistant/raspberrypi4-homeassistant" to "homeassistant/home-assistant" everything works like a charm.
