### ISSUE TITLE
no module requests

### ISSUE THREAD

**Issue by ghost** [sampsyo/hass-smartthinq#112]
when i do python3 example.py -c US -l en-US 
![image](https://user-images.githubusercontent.com/107980295/207702432-036998ce-f721-4a82-a52f-0f826ec3f62d.png)

**Comment by sampsyo** [comment]
You will need to `pip install requests` or similar. Or you can `flit install` in the `wideq` directory!

**Comment by ghost** [comment]
how do you mean flit instan in the wideq directory?

**Comment by sampsyo** [comment]
Yep!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/107980295/207944409-99cb87c2-272f-4ece-a3f2-e17e31d07901.png) ?

**Comment by ghost** [comment]
btw i use a synology nas

**Comment by sampsyo** [comment]
You will need to install [Flit](https://flit.pypa.io/en/stable/)…

**Comment by ghost** [comment]
i instaled it and everything went alright but when i made my changes in my configuration.yaml this happend
![image](https://user-images.githubusercontent.com/107980295/208500306-54c8719c-1d57-46a3-80bf-942170dbeb50.png)
![image](https://user-images.githubusercontent.com/107980295/208500318-94dbdfb4-323e-492d-9e84-a6edaa590da7.png)

**Comment by ghost** [comment]
can you pls help?

**Comment by GamerBremer** [comment]
pls

**Comment by GamerBremer** [comment]
help!!!!
(my new acc)

**Comment by sampsyo** [comment]
With regrets, this is not a good way to get help. I don't have the capacity to look carefully at your precise machine setup to understand exactly what's wrong. Maybe following some threads on the official HA forums could help with the general issue.
