### ISSUE TITLE
hass 0.96.0 climate refactor breaks hass-smarthinq

### ISSUE THREAD

**Issue by jsmath** [sampsyo/hass-smartthinq#20]
It was necessary for me to delete this smarthinq component in order to upgrade to hass 0.96.  After upgrading, I restored the smarthinq component and it is not working.  It seems the MODES were renamed, as well as other changes.

https://www.home-assistant.io/blog/2019/07/17/release-96/#climate
https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

**Comment by sampsyo** [comment]
Thanks for pointing this out! I've updated the component to use the new climate API.

**Comment by jsmath** [comment]
Great work on this!
