### ISSUE TITLE
"Status update failed." log messages

### ISSUE THREAD

**Issue by dmcc** [sampsyo/hass-smartthinq#3]
I've been seeing these in my Home Assistant log. I changed the retry-sleep from 1s to 10s and it seemed to go away. Is anyone else seeing this message?

**Comment by sampsyo** [comment]
Here's the deal with that message: sometimes, the request to get a status update from a device fails. That seems to be fairly normal when first communicating with the device, but it can also happen periodically. Every time HA wants to refresh the device's state, it tries 5 times (as you discovered, 1 second apart)—that's usually enough for me. Maybe increasing the number of retries, or using an exponential backoff to wait longer in later iterations, would be better?

**Comment by gladhorn** [comment]
I assume this issue has been fixed then and can be closed?

**Comment by sampsyo** [comment]
Indeed; let's close it.
