### ISSUE TITLE
Error during setup of component smartthinq

### ISSUE THREAD

**Issue by jptrsn** [sampsyo/hass-smartthinq#37]
I'm not able to get the smartthinq custom component to load properly. I followed the directions in the readme file, but keep getting this error when I restart Home Assistant:

> Error during setup of component smartthinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq/__init__.py", line 68, in setup
    client = wideq.Client.from_token(refresh_token, region, language)
TypeError: from_token() takes 2 positional arguments but 4 were given

I've looked but couldn't find anyone else referencing this problem, and I can't sort it out myself.

**Comment by sampsyo** [comment]
Hi! That indicates a version of wideq that is too old. If you update to the latest version, this should go away.

**Comment by jptrsn** [comment]
I had just cloned the wideq repository this morning. How would I go about updating the version installed with the smartthinq repo? I'm running it in HassIO.

**Comment by sampsyo** [comment]
Huh; I’m not sure why it would get the wrong version. I don’t know about Hass.io, but the usual way to install the latest version of a package such as wideq is with pip.
