### ISSUE TITLE
Support for dryer, washing mashine and fridge

### ISSUE THREAD

**Issue by sagitt** [sampsyo/hass-smartthinq#46]
is possible add this devices ?

thanks for your work

**Comment by towerhand** [comment]
This new repo have support for the washers and it's really easy install/use.
https://github.com/ollo69/ha-smartthinq-washer

**Comment by sagitt** [comment]
Very good. But how configure it?

**Comment by towerhand** [comment]
There’s a PR to fix the read me. Ask further questions in the proper repo
