### ISSUE TITLE
Not working "example.py" in Spain?

### ISSUE THREAD

**Issue by Pharizna** [sampsyo/hass-smartthinq#5]
Hi
I've installed wideq, etc and changed COUNTRY to "SP" and LANGUAGE to "sp-SP" and obtain the URL

https://us.m.lgaccount.com/login/sign_in?authSvr=oauth2&svcCode=SVC202&language=sp-SP&client_id=LGAO221A02&country=SP&division=ha&grant_type=password

but when tried lo log in ... appears an error :(

![image](https://user-images.githubusercontent.com/3939655/41675895-42ba2420-74c4-11e8-8906-67418a816f2c.png)

I've just created a new account in USA server but the problem remains :(

Thank you in advance for your help

**Comment by sampsyo** [comment]
Strange! I’m not familiar with that error. Is it suggesting that there’s no network connection? Very strange!

**Comment by Pharizna** [comment]
Really it’s very strange because, as you can see, I can surf without any problem but not from that URL :(

**Comment by bmwm69** [comment]
@Pharizna  and @sampsyo 

It's easy resolve that problem , you only need edit wideq.py 

COUNTRY = 'US'
LANGUAGE = 'en-US'

to 

COUNTRY = 'es'
LANGUAGE = 'es-ES'

**Comment by Pharizna** [comment]
Thank you @bmwm69 !

Now, I have the token ... but the platform doesn't work properly  and I going to open a new Issue :(
