### ISSUE TITLE
Update to support new entity naming convention?

### ISSUE THREAD

**Issue by monsieurlatte** [sampsyo/hass-smartthinq#54]
Just curious if you have plans on fixing this? 

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 7:29:06 PM (1 occurrences)
Last logged: 7:29:06 PM

ClimateDevice is deprecated, modify LGDevice to extend ClimateEntity

**Comment by sampsyo** [comment]
That's the first I'm hearing of this deprecation! Yes, sounds good, let's address it—but it would be great to put it behind a version check so it's still possibly to use this component with older versions of HomeAssistant for a little while, until it ages out. Want to take a shot at that?

**Comment by monsieurlatte** [comment]
Here's the info, doesnt appear to cause issues with older versions of HA.  
https://developers.home-assistant.io/blog/2020/05/14/entity-class-names

**Comment by sampsyo** [comment]
Great! That `try`/`except` would be the right way to preserve compatibility. Now accepting PRs if anyone has a moment to add that in!

**Comment by monsieurlatte** [comment]
So you're wanting one of us to update this code to fix this?

**Comment by sampsyo** [comment]
Yeah! Pull requests would be super helpful.

**Comment by RomanSladecek** [comment]
Pls anybody with update?

**Comment by jsmath** [comment]
Temporary fix: In climate.py, change ClimateDevice to ClimateEntity in one location. Restart home assistant.

**Comment by Xitro01** [comment]
> Temporary fix: In climate.py, change ClimateDevice to ClimateEntity in one location. Restart home assistant.

I tried this, but did not seem to work.
I changed row 92: `class LGDevice(climate.ClimateEntity):`

Still getting errors that the climate entity is not available.

**Comment by jsmath** [comment]
Not sure, the above change fixed it for me.  I'm assuming you had it working previously?  Make sure you are on the latest home assistant version for this to work. (v 0.110 or later).

**Comment by Xitro01** [comment]
> Not sure, the above change fixed it for me. I'm assuming you had it working previously? Make sure you are on the latest home assistant version for this to work. (v 0.110 or later).

Yes, previously working until I updated to v0.110.7. I saw there was a new update so I'm now on v0.111, but still this issue after the change above:
"SmartThinQ Error
SmartThinQ device not available: AIRCONDITIONER"

Edit: Nevermind, somehow the Airconditioner seems to have completely lost it's wifi connection. Now up 'n running again!

**Comment by mihail4anov** [comment]
> Temporary fix: In climate.py, change ClimateDevice to ClimateEntity in one location. Restart home assistant.

My LG conditioner dissapeared from HA. I also dont see any climate devise in status page.
