### ISSUE TITLE
add .gitignore for __pycache__

### ISSUE THREAD

**Issue by hmoffatt** [sampsyo/hass-smartthinq#56]
Can you please add a .gitignore with an entry to ignore the __pycache__ subdirectory?

I cloned this repo into my homeassistant custom_components as recommended in the README. When I run homeassistant python is creating __pycache__, which causes the smartthingq checkout to appear as having unstaged files.

**Comment by sampsyo** [comment]
Hello! It is generally a really good idea to add things like this to your [global .gitignore](https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer).

No objections to adding it to this repo too, of course—please open a PR if you like!
