### ISSUE TITLE
google autentication issue

### ISSUE THREAD

**Issue by Btje1977** [sampsyo/hass-smartthinq#97]
Somehow the redirection url is not ok when using a google account:

Fout 400: redirect_uri_mismatch
The redirect URI in the request, https://nl.m.lgaccount.com/spx/login/signInGoogle, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

**Comment by sampsyo** [comment]
Yep; I don't believe Google login works (there are other similar issues to be scanned if you are curious).
